# Generated by Django 4.2.26 on 2026-01-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
